export const USERS_FETCH_START='USER_FETCH_START';
export const USERS_FETCH_SUCCESS='USER_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE='USER_FETCH_FAILURE';
export const USER_ADD='USERS_ADD';
export const USER_UPDATE='USERS_UPDATE';
export const USER_DELETE='USER_DELETE';
